Add hosts
Sinfonietta/hostfiles pull request #159
Opened 2021-12-04 11:13 UTC by cityofships

2021-12-04 20:01 UTC, spirillen commented on pornography-hosts
> +0.0.0.0 bngpt.com
https://mypdns.org/my-privacy-dns/matrix/-/issues/3415

2021-12-04 20:01 UTC, spirillen commented on pornography-hosts
> +0.0.0.0 nsfw.xxx
https://mypdns.org/my-privacy-dns/porn-records/-/issues/1777

2021-12-04 20:02 UTC, spirillen commented on pornography-hosts
> +0.0.0.0 pinayflix.tv
https://mypdns.org/my-privacy-dns/porn-records/-/issues/1588

2021-12-04 20:02 UTC, spirillen commented on pornography-hosts
> +0.0.0.0 porntn.com
https://mypdns.org/my-privacy-dns/porn-records/-/issues/110

2021-12-04 20:03 UTC, spirillen commented on pornography-hosts
> +0.0.0.0 promo-bc.com
https://mypdns.org/my-privacy-dns/matrix/-/issues/1087

2021-12-04 20:04 UTC, spirillen commented on pornography-hosts
> +0.0.0.0 www.porntn.com
https://mypdns.org/my-privacy-dns/porn-records/-/issues/110

2021-12-04 20:06 UTC, spirillen requested changes
You are clearly violating my license 

You are to add

1. the license
2. credit the source of work

https://mypdns.org/my-privacy-dns/porn-records/-/blob/master/LICENSE

2021-12-13 21:09 UTC, cityofships commented
> You are clearly violating my license
> 
> You are to add
> 
> 1. the license
> 2. credit the source of work
> 
> https://mypdns.org/my-privacy-dns/porn-records/-/blob/master/LICENSE

?

@Sinfonietta

2021-12-13 21:15 UTC, spirillen commented
> > You are clearly violating my license
> > You are to add
> > 
> > 1. the license
> > 2. credit the source of work
> > 
> > https://mypdns.org/my-privacy-dns/porn-records/-/blob/master/LICENSE
> 

This is not to Sinfonietta, this is to you @cityofships, these records seems more than likely to have been copied from my project as linked, and without a link and information about the LICENSE type you are in violation of the license and copyright.

Please fix it @cityofships you are free to use, redistribute etc. free of charge as long as the two issues are solved.

2021-12-15 21:58 UTC, Sinfonietta commented
Sorry @cityofships I have blocked that Spirillen guy.  So annoying.

2021-12-15 22:07 UTC, merged